version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "5557:5557"
    volumes:
      - ${PWD:-.}/knowledge_base:/app/knowledge_base
      - ${PWD:-.}/behavior_model:/app/behavior_model
      - ${PWD:-.}/vector_store:/app/vector_store
      - ${PWD:-.}/local_models:/app/local_models
    environment:
      - PIP_NO_CACHE_DIR=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - LLM_MODEL=llama3.2:3b
      - USE_CHROMA=true
      - HYBRID_WEIGHT=0.7
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3.0'
        reservations:
          memory: 3G
          cpus: '1.5'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5556:5556"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5557
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
