version: '3.8'

services:
  ollama-ai-project:
    image: ollama/ollama:latest
    container_name: ollama-ai-project
    ports:
      - "11435:11434"
    volumes:
      - ollama_ai_project_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5557:5557"
    volumes:
      - ./knowledge_base:/app/knowledge_base
    env_file:
      - .env
    environment:
      - PIP_NO_CACHE_DIR=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama-ai-project:11434
    depends_on:
      - ollama-ai-project
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5556:5556"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5557
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  ollama_ai_project_data:
