FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY knowledge_base ./knowledge_base
COPY .env .

CMD ["python", "server.py"]
