version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5557:5557"
    volumes:
      - ./knowledge_base:/app/knowledge_base
    env_file:
      - .env
    environment:
      - PIP_NO_CACHE_DIR=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5556:5556"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5557
